name: Official Build and Publish

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install deps
      run: yarn --frozen-lockfile
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v1.3.0
      with:
        github-token: ${{ secrets.github_token }}
    - name: Publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn publish --non-interactive